matrix:
  include:
    - language: cpp
      compilers:
        - g++
        - clang++
      os:
        - linux
        - osx
    - language: c
      compilers:
        - gcc
        - clang
      os:
        - linux
        - osx

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - make test
